game:
  required-players-to-start: 10
  lobby:
    spawn-locations:
      - "spawn:0:0:0:0:0;1"
      - "spawn:0:0:0:0:0;1"
      - "spawn:0:0:0:0:0;1"
      - "spawn:0:0:0:0:0;1"
      - "spawn:0:0:0:0:0;1"
